Resources:
  WidgetsWidgetStore0ED7FDB7:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/WidgetStore/Resource
  WidgetsWidgetHandlerServiceRole8C2B589C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/WidgetHandler/ServiceRole/Resource
  WidgetsWidgetHandlerServiceRoleDefaultPolicyA8E097C8:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - WidgetsWidgetStore0ED7FDB7
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - WidgetsWidgetStore0ED7FDB7
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: WidgetsWidgetHandlerServiceRoleDefaultPolicyA8E097C8
      Roles:
        - Ref: WidgetsWidgetHandlerServiceRole8C2B589C
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/WidgetHandler/ServiceRole/DefaultPolicy/Resource
  WidgetsWidgetHandler1BC9DB34:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4S3Bucket5DF79E03
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4S3VersionKeyE046122D
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4S3VersionKeyE046122D
      Handler: widgets.handler
      Role:
        Fn::GetAtt:
          - WidgetsWidgetHandlerServiceRole8C2B589C
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          BUCKET:
            Ref: WidgetsWidgetStore0ED7FDB7
    DependsOn:
      - WidgetsWidgetHandlerServiceRoleDefaultPolicyA8E097C8
      - WidgetsWidgetHandlerServiceRole8C2B589C
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/WidgetHandler/Resource
      aws:asset:path: /Users/casa/cgradwohl/projects/habitual-cdk/assets
      aws:asset:property: Code
  Widgetswidgetsapi72353315:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: This service serves widgets.
      Name: Widget Service
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Resource
  WidgetswidgetsapiDeployment406A9BD6d8a8c5c28e977f31e39422f9b0345154:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: Widgetswidgetsapi72353315
      Description: Automatically created by the RestApi construct
    DependsOn:
      - WidgetswidgetsapiidDELETEE81619C6
      - WidgetswidgetsapiidGETABE1C648
      - WidgetswidgetsapiidPOST60B9DB49
      - WidgetswidgetsapiidAA19CFA8
      - WidgetswidgetsapiGET2086C825
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Deployment/Resource
  WidgetswidgetsapiDeploymentStageprod0D8CD1B7:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: Widgetswidgetsapi72353315
      DeploymentId:
        Ref: WidgetswidgetsapiDeployment406A9BD6d8a8c5c28e977f31e39422f9b0345154
      StageName: prod
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/DeploymentStage.prod/Resource
  WidgetswidgetsapiCloudWatchRole8C2A5801:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/CloudWatchRole/Resource
  WidgetswidgetsapiAccountDA847A77:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - WidgetswidgetsapiCloudWatchRole8C2A5801
          - Arn
    DependsOn:
      - Widgetswidgetsapi72353315
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Account
  WidgetswidgetsapiGETApiPermissionHabitualCdkStackWidgetswidgetsapi314EE452GETB986B405:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /
            - Ref: WidgetswidgetsapiDeploymentStageprod0D8CD1B7
            - /GET/
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/GET/ApiPermission.HabitualCdkStackWidgetswidgetsapi314EE452.GET..
  WidgetswidgetsapiGETApiPermissionTestHabitualCdkStackWidgetswidgetsapi314EE452GETC11ACDFC:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/GET/ApiPermission.Test.HabitualCdkStackWidgetswidgetsapi314EE452.GET..
  WidgetswidgetsapiGET2086C825:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - Widgetswidgetsapi72353315
          - RootResourceId
      RestApiId:
        Ref: Widgetswidgetsapi72353315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: '{ "statusCode": "200" }'
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WidgetsWidgetHandler1BC9DB34
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/GET/Resource
  WidgetswidgetsapiidAA19CFA8:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - Widgetswidgetsapi72353315
          - RootResourceId
      PathPart: "{id}"
      RestApiId:
        Ref: Widgetswidgetsapi72353315
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/Resource
  WidgetswidgetsapiidPOSTApiPermissionHabitualCdkStackWidgetswidgetsapi314EE452POSTid68F0C54C:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /
            - Ref: WidgetswidgetsapiDeploymentStageprod0D8CD1B7
            - /POST/{id}
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/POST/ApiPermission.HabitualCdkStackWidgetswidgetsapi314EE452.POST..{id}
  WidgetswidgetsapiidPOSTApiPermissionTestHabitualCdkStackWidgetswidgetsapi314EE452POSTid1C14B774:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /test-invoke-stage/POST/{id}
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/POST/ApiPermission.Test.HabitualCdkStackWidgetswidgetsapi314EE452.POST..{id}
  WidgetswidgetsapiidPOST60B9DB49:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: WidgetswidgetsapiidAA19CFA8
      RestApiId:
        Ref: Widgetswidgetsapi72353315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WidgetsWidgetHandler1BC9DB34
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/POST/Resource
  WidgetswidgetsapiidGETApiPermissionHabitualCdkStackWidgetswidgetsapi314EE452GETidCA4C1895:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /
            - Ref: WidgetswidgetsapiDeploymentStageprod0D8CD1B7
            - /GET/{id}
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/GET/ApiPermission.HabitualCdkStackWidgetswidgetsapi314EE452.GET..{id}
  WidgetswidgetsapiidGETApiPermissionTestHabitualCdkStackWidgetswidgetsapi314EE452GETid0625F32A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /test-invoke-stage/GET/{id}
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/GET/ApiPermission.Test.HabitualCdkStackWidgetswidgetsapi314EE452.GET..{id}
  WidgetswidgetsapiidGETABE1C648:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: WidgetswidgetsapiidAA19CFA8
      RestApiId:
        Ref: Widgetswidgetsapi72353315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WidgetsWidgetHandler1BC9DB34
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/GET/Resource
  WidgetswidgetsapiidDELETEApiPermissionHabitualCdkStackWidgetswidgetsapi314EE452DELETEid23CF5994:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /
            - Ref: WidgetswidgetsapiDeploymentStageprod0D8CD1B7
            - /DELETE/{id}
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/DELETE/ApiPermission.HabitualCdkStackWidgetswidgetsapi314EE452.DELETE..{id}
  WidgetswidgetsapiidDELETEApiPermissionTestHabitualCdkStackWidgetswidgetsapi314EE452DELETEidE908E5F9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WidgetsWidgetHandler1BC9DB34
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Widgetswidgetsapi72353315
            - /test-invoke-stage/DELETE/{id}
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/DELETE/ApiPermission.Test.HabitualCdkStackWidgetswidgetsapi314EE452.DELETE..{id}
  WidgetswidgetsapiidDELETEE81619C6:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: DELETE
      ResourceId:
        Ref: WidgetswidgetsapiidAA19CFA8
      RestApiId:
        Ref: Widgetswidgetsapi72353315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WidgetsWidgetHandler1BC9DB34
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: HabitualCdkStack/Widgets/widgets-api/Default/{id}/DELETE/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.36.1,@aws-cdk/assets=1.36.1,@aws-cdk/aws-apigateway=1.36.1,@aws-cdk/aws-cloudwatch=1.36.1,@aws-cdk/aws-ec2=1.36.1,@aws-cdk/aws-events=1.36.1,@aws-cdk/aws-iam=1.36.1,@aws-cdk/aws-kms=1.36.1,@aws-cdk/aws-lambda=1.36.1,@aws-cdk/aws-logs=1.36.1,@aws-cdk/aws-s3=1.36.1,@aws-cdk/aws-s3-assets=1.36.1,@aws-cdk/aws-sqs=1.36.1,@aws-cdk/aws-ssm=1.36.1,@aws-cdk/cloud-assembly-schema=1.36.1,@aws-cdk/core=1.36.1,@aws-cdk/cx-api=1.36.1,@aws-cdk/region-info=1.36.1,jsii-runtime=node.js/v12.16.2
    Condition: CDKMetadataAvailable
Outputs:
  WidgetswidgetsapiEndpoint5B785C68:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: Widgetswidgetsapi72353315
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: WidgetswidgetsapiDeploymentStageprod0D8CD1B7
          - /
Parameters:
  AssetParameters1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4S3Bucket5DF79E03:
    Type: String
    Description: S3 bucket for asset "1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4"
  AssetParameters1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4S3VersionKeyE046122D:
    Type: String
    Description: S3 key for asset version "1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4"
  AssetParameters1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4ArtifactHash036C93A7:
    Type: String
    Description: Artifact hash for asset "1eee885a2d697a96455c8f45f3125103953d21b3bf5fc989d24f14f468ef32f4"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

